name: Build & Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application Container
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Google Setup
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Docker Build
        run: docker build -t gcr.io/$PROJECT_ID/demo-app .

      - name: Docker Push
        run: |
          gcloud auth configure-docker -q
          docker push gcr.io/$PROJECT_ID/demo-app

  deploy:
    name: Deploy Application to Cloud Run
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Google Setup
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "github-actions-demo"
          image: "gcr.io/${{ secrets.PROJECT_ID }}/demo-app"
