name: Code Quality Checks

on: push

jobs:
  prettier:
    name: Prettier Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: apply prettier changes"
  
